version: "2.4"
services:
  docker_qt_opt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: docker_qt_opt
    tty: true
    cap_add:
      - SYS_NICE
    environment:
      - CUDA_VISIBLE_DEVICES=0
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    privileged: true
    devices:
    - /dev:/dev
    runtime: nvidia
    volumes:
      # - ../../calibration:/root/git/calibration
      - ../git:/root/git

